%YAML:1.0
File.version: "1.0"
Camera.type: "Rectified"
Camera1.fx: 721.5377
Camera1.fy: 721.5377
Camera1.cx: 609.5593
Camera1.cy: 172.854
Stereo.b: 0.5327254279298227
Camera.width: 1242
Camera.height: 375
Camera.fps: 10
Camera.RGB: 1
Stereo.ThDepth: 35.0
ORBextractor.nFeatures: 1250
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
DataSetPath: /home/brain/DataSet/KITTI-Raw/2011_09_26_drive_0052_sync/2011_09_26/2011_09_26_drive_0052_sync/
MinSemanticConfidence: 0.1
MOT: 1
Pc_v: !!opencv-matrix
   rows: 3
   cols: 4
   dt: f
   data: [ -0.74, 0.86,  -0.74,  0.86,
           1.68, 1.68,  1.68, 1.68,
           1.65, 1.65, -1.06,  -1.06 ]
