%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Right Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 545.7402000594014
Camera1.fy: 546.4624873938807
Camera1.cx: 516.7898455908171
Camera1.cy: 399.68834148863493

# distortion parameters
Camera1.k1: -0.06983837053126551
Camera1.k2: 0.030679193251357234
Camera1.p1: -0.029318268716673087
Camera1.p2: 0.008383563478792275

# Camera resolution
Camera.width: 1024
Camera.height: 768

# Camera frames per second 
Camera.fps: 12

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

Stereo.ThDepth: 40.0
Stereo.b: 0.095

# Depth map values factor
RGBD.DepthMapFactor: 1000.0

# Transformation from body-frame (imu) to left camera
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [-0.9999193557683889,-0.007982464004835765,0.009877359370849279,0.0464263767074247,
         0.0078087424182379074,-0.9998163145030406,-0.017503165296644745,0.11439387763182247,
         0.010015263430135759,-0.017424624012229308,0.9997980180898823,-0.007855822145540904,
         0.0,0.0,0.0,1.0]


# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 0

# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 0.00046306229509090514  # 3 # 2.44e-4 #1e-3 # rad/s^0.5
IMU.NoiseAcc:  0.0007970737515806496    #2 # 1.47e-3 #1e-2 # m/s^1.5
IMU.GyroWalk: 9.798339194666108e-07 # rad/s^1.5
IMU.AccWalk: 4.134509826460877e-06  # m/s^2.5
IMU.Frequency: 200.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1250

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
