%YAML:1.0

Camera1.fx: 517.306408
Camera1.fy: 516.469215
Camera1.cx: 318.643040
Camera1.cy: 255.313989

Camera1.k1: 0.262383
Camera1.k2: -0.953104
Camera1.p1: -0.005358
Camera1.p2: 0.002628
Camera1.k3: 1.163314

Camera.width: 640
Camera.height: 480

CameraRGBD.b: 0.07732

CameraRGBD.DepthMapFactor: 5000.0

# Camera frames per second 
Camera.fps: 30.0

# IR projector baseline times fx (aprox.)
Camera.bf: 40.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Depth threshold
ThDepth: 40.0

# Deptmap values factor 
DepthMapFactor: 5000.0


#=======================================Features=======================================
Features.MaxNumber: 500
Features.MinRadius: 30

#=======================================Local Optimization=======================================
Optimizer.ActiveWindowSize: 10
Optimizer.FixedWindowSize: 3

#=======================================Visualization=======================================
Viewer.Open: 1
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.PointSize: 2.0
Viewer.ViewPointX: 0.0
Viewer.ViewPointY: -0.7
Viewer.ViewPointZ: -1.8
Viewer.ViewPointF: 500.0

