%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 597.5844576903867
Camera1.fy: 595.6975648168125
Camera1.cx: 503.84745069436934
Camera1.cy: 363.9658543757647

Camera1.k1: -0.10545577776819674
Camera1.k2: 0.07514716057622699
Camera1.p1: -0.0005332396331567457
Camera1.p2: 0.00043194556571626917

Camera2.fx: 596.7165106270432
Camera2.fy: 596.1773471643659
Camera2.cx: 509.2537639920017
Camera2.cy: 374.96361346949357

Camera2.k1: -0.1100878619846527
Camera2.k2: 0.08480722678555397
Camera2.p1:  -0.00013267693422274322
Camera2.p2: -0.0023990053029366927

Camera.width: 1024
Camera.height: 768

# Camera frames per second 
Camera.fps: 20

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

Stereo.ThDepth: 60.0
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [0.99890269, -0.02264661, -0.04099457,  0.25131046,
        0.02307396,  0.99968393,  0.00998163,  0.00490523,
        0.04075556, -0.01091658,  0.99910951, -0.01260669,
        0.,          0.,          0. ,         1.        ]


# Transformation from camera to body-frame (imu)
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [-0.0160927, -0.0168493,   0.999729, -0.0052537,
        -0.999683, -0.0190891, -0.0164137, 0.0664483,
        0.0193604,  -0.999676, -0.0165368, 0.0142414,
        0. ,         0. ,         0.    ,      1.  ]


# IMU noise
IMU.NoiseGyro: 1.7e-4 #1.6968e-04
IMU.NoiseAcc: 2.0000e-3 #2.0e-3
IMU.GyroWalk: 1.9393e-05 
IMU.AccWalk: 3.0000e-03 # 3e-03
IMU.Frequency: 200.0

# time delay: t_imu = t_img + td
TimeDelay: 0.44

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0

