%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 594.2427102128038
Camera1.fy: 593.1573133838631
Camera1.cx: 507.16706642604424
Camera1.cy: 376.38973291006397

Camera1.k1: -0.11442465184228696
Camera1.k2: 0.07708007126993904
Camera1.p1: 0.0004503383019309241
Camera1.p2: 0.0017918595216045753

Camera2.fx: 594.1265571636687
Camera2.fy: 593.134817369391
Camera2.cx: 511.21575051013076
Camera2.cy: 387.351101278967

Camera2.k1: -0.11883070712708221
Camera2.k2: 0.08157182192462581
Camera2.p1: 0.0010165745084391165
Camera2.p2: 9.070967532159137e-05


Camera.width: 1024
Camera.height: 768

# Camera frames per second 
Camera.fps: 20

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

Stereo.ThDepth: 60.0
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [ 0.99908993, -0.00998402, -0.04146847,  0.25142281,
        0.01056173,  0.99984988,  0.01373571,  0.00465675,
        0.04132511, -0.01416119,  0.99904539, -0.01241141,
        0.,          0.,          0.,          1.        ]


# Transformation from camera to body-frame (imu)
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [ 0.03025075,  0.00054434 , 0.99954219,  0.07993179,
        -0.99922528, -0.0251689 ,  0.03025486 , 0.10555551,
          0.02517385, -0.99968306, -0.00021746,  0.01511945,
          0. ,         0. ,         0.    ,      1.        ]

# IMU noise
IMU.NoiseGyro: 1.7e-4 #1.6968e-04
IMU.NoiseAcc: 2.0000e-3 #2.0e-3
IMU.GyroWalk: 1.9393e-05 
IMU.AccWalk: 3.0000e-03 # 3e-03
IMU.Frequency: 200.0


# time delay: t_imu = t_img + td
TimeDelay: -1.25

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0

